### ISSUE TITLE
Long Path of the lab

### ISSUE THREAD

**Issue by Zahrarjb** [KatharaFramework/Kathara#37] opened 2019-02-20 17:27 UTC
hello,

I wanted to deploy a SDN network using Kathara with 2 Ryu controller as follow:

4 switches,2 RYU controllers and 4 hosts which runs successfully.

while by extending it to 7 switches, 2 controllers,5 hosts, I receive an error which is :
" 
========================= Starting Lab ==========================
Command line too long, probably because of a long path to this lab. Try moving the lab to a shorter path. The status is now corrupted, please run lclean or lwipe.
 "

Both labs were in the same path but I got this error only for the extended version of the scenario. I moved the file to /home directory but still facing the same problem.

Any comment or idea is highly appreciated.

**Comment by Kidel** [comment] 2019-02-20 17:32
Hi! Thank you for using Katharà for your SDN experiments. 

About your error, it should only happen with labs that go way over 300 nodes (and we are looking into that to fix it). 

Can you put your lab in a zip file and drag it into your reply? This way I can try to run it and replicate the error. Also are you on Linux or Windows, because the command limit on Linux is incredibly long. It would also help to know where is Katharà located on your system. 

Anyway I suggest you run `lwipe` just in case, followed by `lstart` of your lab. And please make sure you are using the latest version of the software (as you probably are).

**Comment by Zahrarjb** [comment] 2019-02-20 17:45
Thank you very much for the quick response. Actually, I am new to Kathara and the lab still needs more configuration but I have attached both files here. I have the problem only with SDNSlab2. I am using Linux Ubuntu and the latest version of Kathara.
I used both commands for Lcarsh,lclean and lwipe and again started by lstart but, unfortunately, it didn't work.
[SDNSlab1.tar.gz](https://github.com/KatharaFramework/Kathara/files/2885821/SDNSlab1.tar.gz)
[SDNSlab2.tar.gz](https://github.com/KatharaFramework/Kathara/files/2885823/SDNSlab2.tar.gz)

thank you very much.

**Comment by Kidel** [comment] 2019-03-03 23:43
Hi. Sorry for the late answer. I tested your labs but I wasn't able to reproduce your issue, and everything seems to be working fine. It may be an issue with your configuration. 

Can you please provide the output of the `$NETKIT_HOME/check` command? And also the contents of your Katharà config file. 

Thank you. 

Screen: 
![image](https://user-images.githubusercontent.com/3390842/53703833-8995a880-3e16-11e9-8073-4d4be4ef5311.png)

**Comment by Kidel** [comment] 2019-03-10 15:10
Since there is no reply I'm closing this issue. Please feel free to open a new one to report any bug or idea.

**Closed as completed by Kidel** 2019-03-10 15:10 UTC
