### ISSUE TITLE
Add support to Debian 12

### ISSUE THREAD

**Issue by gabrielepmattia** [KatharaFramework/Kathara#247] opened 2023-10-11 08:19 UTC
### Related Bug

When installing to Debian 12, libssl1.1 is requested but the library is no more provided

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 kathara : Depends: libssl1.1 (>= 1.1.1) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

### Feature Description

The software should work in modern versions of the OS.

**Comment by tcaiazzi** [comment] 2023-10-11 09:42
Hi @gabrielepmattia, 

Thanks for opening the issue! We forgot to update the installation guide for Debian12. 

I have done it now: https://github.com/KatharaFramework/Kathara/wiki/Linux#debian-12

The problem is that old instructions tell to use the `focal` package, instead on Debian12 we need the `jammy` one. 

To fix the installation, follow these steps:

1. Probably you need to delete the Kathará broken entry from `/etc/apt/sources.list.d/kathara.list`
2. Add Kathará public key to your keyring (probably you already have this): 
```
wget -qO - "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x21805a48e6cbba6b991abe76646193862b759810" |  gpg --dearmor -o /usr/share/keyrings/ppa-kathara-archive-keyring.gpg
```
3. Add the `jammy` Kathará repository (not the `focal` one as previously):
	* Create a `kathara.list` file in `/etc/apt/sources.list.d` and put inside the following lines:
        ```
        deb [ signed-by=/usr/share/keyrings/ppa-kathara-archive-keyring.gpg ] http://ppa.launchpad.net/katharaframework/kathara/ubuntu jammy main 
        deb-src [ signed-by=/usr/share/keyrings/ppa-kathara-archive-keyring.gpg ] http://ppa.launchpad.net/katharaframework/kathara/ubuntu jammy main 
        ```
	* Or run the following commands:
        ```
        echo "deb [ signed-by=/usr/share/keyrings/ppa-kathara-archive-keyring.gpg ] http://ppa.launchpad.net/katharaframework/kathara/ubuntu jammy main" |  tee /etc/apt/sources.list.d/kathara.list
        echo "deb-src [ signed-by=/usr/share/keyrings/ppa-kathara-archive-keyring.gpg ] http://ppa.launchpad.net/katharaframework/kathara/ubuntu jammy main" |  tee -a /etc/apt/sources.list.d/kathara.list
        ```
4. Update your apt cache by running: 
```
sudo apt update
```
5. Install Kathará: 
```
sudo apt install kathara
```

If everything works, you should have Kathará 3.7.0 installed. 

<img src="https://github.com/KatharaFramework/Kathara/assets/26346836/a8828a10-e7a1-462e-92dd-8a4b5ed9b566" width="600">

Let me know if you have any problems!

**Comment by tcaiazzi** [comment] 2023-10-17 08:12
Hi @gabrielepmattia,

I'm closing the issue since the problem should be resolved, but feel free to re-open it, if needed :smile:

**Closed as completed by tcaiazzi** 2023-10-17 08:12 UTC
Labels: enhancement, platform/linux
