### ISSUE TITLE
Installation on Ubuntu (arm64 architecture)

### ISSUE THREAD

**Issue by alizandian** [KatharaFramework/Kathara#120] opened 2020-12-27 10:43 UTC
After following installation procedures on Ubuntu (adding repositories and meeting prerequisites), after running the command: 
`sudo apt-get install kathara`
I get this:
`Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package kathara
`
Does it have something to do with arm64 (Using raspberry pi 4)

This is my uname -a results:
Linux jan-desktop 5.8.0-1010-raspi #13-Ubuntu SMP PREEMPT Wed Dec 9 17:14:07 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux

And this is release:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.10
DISTRIB_CODENAME=groovy
DISTRIB_DESCRIPTION="Ubuntu 20.10"
NAME="Ubuntu"
VERSION="20.10 (Groovy Gorilla)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.10"
VERSION_ID="20.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy

**Comment by lorenzo93** [comment] 2020-12-30 15:58
Duplicate of #104

**Closed as completed by lorenzo93** 2020-12-30 15:58 UTC
